from __future__ import annotations

import ast
import io
import re
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

FORBIDDEN = [
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "skeleton",
    "placeholder",
    "todo from paper",
    "state-of-the-art",
    "cutting-edge",
    "seamlessly",
    "delve",
    "holistic",
    "meticulously",
    "it's worth noting",
    "in conclusion",
]

EMOJI = re.compile(
    "[\U0001f300-\U0001faff\U00002600-\U000027bf\U0001f1e6-\U0001f1ff\U00002b00-\U00002bff]"
)


def _python_files() -> list[Path]:
    files: list[Path] = []
    for base in ("ghxattn", "tests"):
        files.extend((ROOT / base).rglob("*.py"))
    return files


def _scannable_files() -> list[Path]:
    return [path for path in _python_files() if path.name != "test_style_guard.py"]


def _prose_files() -> list[Path]:
    candidates = [ROOT / "README.md", ROOT / "Makefile"]
    return [path for path in candidates if path.exists()]


def test_no_comments() -> None:
    for path in _python_files():
        source = path.read_text()
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            assert token.type != tokenize.COMMENT, f"{path}:{token.start[0]}"


def test_no_docstrings() -> None:
    for path in _python_files():
        tree = ast.parse(path.read_text())
        for node in ast.walk(tree):
            if isinstance(node, ast.Module | ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
                assert ast.get_docstring(node) is None, str(path)


def test_no_forbidden_phrases() -> None:
    for path in _scannable_files() + _prose_files():
        text = path.read_text().lower()
        for phrase in FORBIDDEN:
            assert phrase not in text, f"{phrase} in {path}"


def test_no_emoji() -> None:
    for path in _scannable_files() + _prose_files():
        assert EMOJI.search(path.read_text()) is None, str(path)
